### ISSUE TITLE
OpenCV practice ideas

### ISSUE THREAD

**Issue by dkurt** [dkurt/openvino_practice#3]
@l-bat, @allnes

**Comment by allnes** [comment]
1) Matrix filters (smoothing)
2) Work with histogram (equalization)
3) Blending ([example](https://en.wikipedia.org/wiki/Blend_modes#:~:text=Blend%20modes%20(or%20mixing%20modes,layer%20(see%20alpha%20compositing).) ))
4) Work with color spaces
5) Haar's cascade model 
6) Find edges (Sobel)
7) Correlation between images
8) Morphological operations 

@dkurt maybe work with classical CV themes?

**Comment by dkurt** [comment]
Implemented one task with coins counting: https://github.com/dkurt/openvino_practice/pull/37. Covers
* Morphological operations
* Work with color spaces (at least BGR, grayscale and binary)

Additionally, this task helps in future segmentation module where students should count glands: https://github.com/dkurt/openvino_practice/tree/develop/modules/5_segmentation

**Comment by dkurt** [comment]
So, I think it will be good enough with one but complete task rather than separate tasks such open image, apply single filter. Moreover there is a lot of OpenCV usage in almost all the modules so we could say that during their completion students study OpenCV as well.
