### ISSUE TITLE
Semantic / Instance segmentation practice ideas

### ISSUE THREAD

**Issue by dkurt** [dkurt/openvino_practice#6]
@druzhkov-paul, @bes-dev

**Comment by dkurt** [comment]
Have interesting idea for practice or as project proposal (projects are done by teams during the Intel Summer Camp). Inspired by https://twitter.com/foka22ok/status/1265213326998384642, need to create a sample which detects specific classes and does periodic smooth resizing by semantic or instance segmentation masks. Finally, it can process a video file with audio track. The period might be constant or (for advanced students) determined from audio track.

**Comment by druzhkov-paul** [comment]
Object removal application (in a restricted environment, for sure) of some kind might be a reasonable choice here, IMHO. Details may vary, but as an example, it may closely follow the logic of the [whiteboard inpainting demo](https://github.com/opencv/open_model_zoo/pull/1066) and be powered by either semantic of instance segmentation. Whiteboard use case is just one example. In general, objects' removal may be carried out in any video or a batch of images captured by a static camera by coping content for the masked areas from complementary frames/images. As a more sophisticated example, image/video inpainting networks might be used for filling the masked regions.

**Comment by druzhkov-paul** [comment]
Some kind of image-to-image translation application is also an option. General pipeline is as follows: produce semantic segmentation for a given image -> transform/edit segmentation (for example, replace all buildings' pixels with trees) -> generate an image back from segmentation labels map. This being said, this is more of a GANs demo, than a segmentation one, but anyway.

Useful links:
* [pix2pixHD](https://github.com/NVIDIA/pix2pixHD)
* [SPADE](https://github.com/NVlabs/SPADE)
* [vid2vid](https://github.com/NVIDIA/vid2vid)

**Comment by dkurt** [comment]
@druzhkov-paul, Thanks!

Yes, I think that's good point that we can combine segmentation with masked style transfer or pix2pix.

**Comment by dkurt** [comment]
* segmentation module: https://github.com/dkurt/openvino_practice/tree/develop/modules/5_segmentation
* GAN module: https://github.com/dkurt/openvino_practice/tree/develop/modules/7_colorization
