### ISSUE TITLE
Quantization, network optimization practice ideas

### ISSUE THREAD

**Issue by dkurt** [dkurt/openvino_practice#8]
@AlexKoff88, @alexsu52

**Comment by AlexKoff88** [comment]
- Quantize MobileNet v2 Cifar-100 with POT. It is doable even on Windows laptops. I checked this.

**Comment by dkurt** [comment]
@AlexKoff88, do you have some references to trained model?

**Comment by AlexKoff88** [comment]
Sure. I have the model in the IR and the corresponding configs in the internal share.

**Comment by dkurt** [comment]
Created a PR: https://github.com/dkurt/openvino_practice/pull/41. Decided to use another public network - style transfer. Tasks are
1. Run FP32 network
2. Quantize network on MSCOCO validation subset (just generic images)
3. Run INT8 network with Telegram bot

**Comment by AlexKoff88** [comment]
The validation process can take a lot of time in this case even on a desktop. Have you tried it?

**Comment by dkurt** [comment]
Yes, 300 samples on Core i5 take about 3-4 minutes (network is pretty fast). The following are outputs from origin and quantized networks (here almost similar but for different images just different patterns are observed, no bad artifacts):

| FP32 output | INT8 output|
|---|---|
| <img src="https://user-images.githubusercontent.com/25801568/86325371-96175480-bc48-11ea-8af9-fb562c1b0031.png" width="256">|  <img src="https://user-images.githubusercontent.com/25801568/86325404-a3344380-bc48-11ea-8b45-03cafcde5c43.png" width="256">|

Network is reshapable and works fine on any resolution. For this image (839x501) it gives about 0.43 second on INT8 versus 0.9 on FP32

**Comment by AlexKoff88** [comment]
Ok, this is really fast. No problem then.
